version: '2'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle-data:/usr/local/bundle

  db:
    build: db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  bundle-data:
    driver: local
  mysql-data:
    driver: local
